#pragma once

#include <Arduino.h>

#define     EMPTY       0
#define     GROUND      1
#define     SCALE       2
#define     CABLE       3
#define     ENDSCALE    4
#define     TREASURE    5
#define     HERO        6
#define     ENNEMY      7

uint8_t  constexpr LEVEL_WIDTH  = 28;
uint8_t  constexpr LEVEL_HEIGHT = 16;
uint16_t constexpr LEVEL_SIZE   = LEVEL_WIDTH * LEVEL_HEIGHT;
uint8_t  constexpr LEVEL_NUMBER = 2;

uint8_t const constexpr LEVEL_PLAYER_START[] = {
     2, 14, // Level 1
    16, 14  // Level 2
};

uint8_t const constexpr LEVEL_MAP[] PROGMEM = {

// Level 1
EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   ENDSCALE,EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,
EMPTY,   EMPTY,   EMPTY,   TREASURE,EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   ENDSCALE,EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,
GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  SCALE,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  EMPTY,   EMPTY,   EMPTY,   ENDSCALE,EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,
EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   ENDSCALE,EMPTY,   EMPTY,   EMPTY,   EMPTY,   TREASURE,EMPTY,   EMPTY,   EMPTY,   EMPTY,
EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   GROUND,  GROUND,  SCALE,   EMPTY,   EMPTY,   EMPTY,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  SCALE,   GROUND,  GROUND,
EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   GROUND,  GROUND,  SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,
EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   ENNEMY,  EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   GROUND,  GROUND,  SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   TREASURE,ENNEMY,  EMPTY,   SCALE,   EMPTY,   EMPTY,
GROUND,  GROUND,  SCALE,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  EMPTY,   EMPTY,   EMPTY,   EMPTY,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  SCALE,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,
EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,
EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   ENNEMY,  EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,
GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  SCALE,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,
EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,
EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   TREASURE,EMPTY,   SCALE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   SCALE,   EMPTY,   EMPTY,   EMPTY,   TREASURE,EMPTY,   EMPTY,   EMPTY,
EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  SCALE,
EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   HERO,    EMPTY,   EMPTY,   TREASURE,EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,
GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,

// Level 2
EMPTY,   EMPTY,   EMPTY,   TREASURE,EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   ENDSCALE,
SCALE,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   TREASURE,EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   ENDSCALE,
SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  SCALE,   EMPTY,   TREASURE,EMPTY,   EMPTY,   EMPTY,   ENDSCALE,
SCALE,   EMPTY,   TREASURE,EMPTY,   ENNEMY,  EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  ENDSCALE,
SCALE,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   ENDSCALE,
SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   CABLE,   CABLE,   CABLE,   CABLE,   SCALE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   EMPTY,   EMPTY,   ENNEMY,  SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   ENDSCALE,
SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  SCALE,
SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   TREASURE,EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,
SCALE,   EMPTY,   EMPTY,   EMPTY,   ENNEMY,  EMPTY,   SCALE,   EMPTY,   TREASURE,EMPTY,   EMPTY,   SCALE,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,
GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   GROUND,  GROUND,  GROUND,  SCALE,   GROUND,  GROUND,
GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,
GROUND,  TREASURE,EMPTY,   EMPTY,   GROUND,  EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   CABLE,   SCALE,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   TREASURE,
GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  SCALE,   GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   GROUND,  GROUND,  GROUND,  GROUND,
EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,
EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   HERO,    EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   SCALE,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,   EMPTY,
GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,  GROUND,


};

/**
 * ----------------------------------------------------------------------------
 * Lode Runner game bootstrap
 * ----------------------------------------------------------------------------
 * Copyright (c) 2022 Stéphane Calderoni (https://github.com/m1cr0lab)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 * ----------------------------------------------------------------------------
 */